# Generated by Django 3.0 on 2024-12-21 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('photo', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tribes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('culture', models.CharField(max_length=100)),
                ('population_size', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('traditional_occupation_on_jobs', models.CharField(max_length=100)),
                ('caste_and_religion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tribal_related_problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('problem', models.CharField(max_length=100)),
                ('photo', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('TRIBE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Tribes')),
            ],
        ),
        migrations.CreateModel(
            name='Tribal_member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=100)),
                ('relation', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('TRIBE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Tribes')),
            ],
        ),
        migrations.CreateModel(
            name='Request_entry_service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('COORDINATER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Coordinater')),
                ('TRIBE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Tribes')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('COORDINATER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Coordinater')),
            ],
        ),
        migrations.CreateModel(
            name='Food_and_medical_supply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=100)),
                ('COORDINATER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Coordinater')),
                ('TRIBE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Tribes')),
            ],
        ),
        migrations.CreateModel(
            name='District_officer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('photo', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pin', models.CharField(max_length=100)),
                ('workingdistrict', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Login')),
            ],
        ),
        migrations.CreateModel(
            name='Councilors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('photo', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Login')),
            ],
        ),
        migrations.AddField(
            model_name='coordinater',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Login'),
        ),
        migrations.CreateModel(
            name='Allocate_package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('alloted_amount', models.CharField(max_length=100)),
                ('PACKAGE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Package')),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('TRIBE_RELATED_PROBLEM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Tribal_related_problem')),
            ],
        ),
    ]
