# Generated by Django 3.0 on 2024-12-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='allocate_package',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='coordinater',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='councilors',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='district_officer',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='request_entry_service',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tribal_member',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tribal_related_problem',
            name='date',
            field=models.DateField(),
        ),
    ]
